[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "ckf"
dependencies = []

[tool.setuptools.packages.find]
where = ["src/"]
include = ["ckf"]